kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: kcsc-csi-toolprovider
spec:
  selector:
    matchLabels:
      app: kcsc-csi-toolprovider
  template:
    metadata:
      labels:
        app: kcsc-csi-toolprovider
    spec:
      hostNetwork: true
      containers:
        - name: node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/toolprovider.csi.kcsc-reg.sock"]
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/kcsc-csi-toolprovider/socket/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
          - mountPath: /registration
            name: registration-dir

        - name: toolprovider
          image: quay.io/dfestal/toolproviderplugin:canary
          ports:
            - name: web
              containerPort: 8080  
          args:
            - "--v=2"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - mountPath: /var/lib/containers/storage
              mountPropagation: Bidirectional
              name: storageroot-dir
            - mountPath: /var/lib/shared
              mountPropagation: Bidirectional
              readOnly: true
              name: additional-storageroot-dir
            - mountPath: /var/run/containers/storage
              mountPropagation: Bidirectional
              name: storagerunroot-dir
            - mountPath: /var/run/toolprovider-metadata-store
              name: metadata-store-dir
            - mountPath: /etc/toolprovider-catalog-config
              name: catalog-config
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/kcsc-csi-toolprovider/socket
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
          name: mountpoint-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          name: registration-dir
        - hostPath:
            path: /var/lib/containers/storage
            type: DirectoryOrCreate
          name: additional-storageroot-dir
        - hostPath:
            path: /var/lib/kubelet/plugins/kcsc-csi-toolprovider/metadata-store-dir
            type: DirectoryOrCreate
          name: metadata-store-dir
        - hostPath:
            path: /var/lib/kubelet/plugins/kcsc-csi-toolprovider/storageroot-dir
            type: DirectoryOrCreate
          name: storageroot-dir
        - hostPath:
            path: /var/lib/kubelet/plugins/kcsc-csi-toolprovider/storagerunroot-dir
            type: DirectoryOrCreate
          name: storagerunroot-dir
        - configMap:
            name: kcsc-csi-toolprovider
          name: catalog-config

