kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: catalog-pull
spec:
  selector:
    matchLabels:
      app: catalog-pull
  template:
    metadata:
      labels:
        app: catalog-pull
    spec:
      containers:
        - name: jdk
          image: >-
            quay.io/dfestal/csi-tool-openjdk11u-jdk_x64_linux_hotspot_11.0.9.1_1:latest
          imagePullPolicy: Always
        - name: maven
          image: 'quay.io/dfestal/csi-tool-maven-3.6.3:latest'
          imagePullPolicy: Always
